spring:
  datasource:
    url: ${APP_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${APP_DATASOURCE_USERNAME}
    password: ${APP_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#    generate-ddl: true