apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  namespace: {{ .Values.namespace }}
  labels:
    product: TestApplication
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      release: {{ .Values.deploymentName }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        release: {{ .Values.deploymentName }}
        product: TestApplication
        env: {{ .Values.env }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imageSecret }}
      containers:
        - name: {{ .Values.deploymentName }}
          image: {{ .Values.imageName }}
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 8080
          env:
            - name: PROFILE
              value: {{ .Values.env }}
          envFrom:
            - configMapRef:
                name: {{ .Values.deploymentName }}-configmap
